name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the action on push to main branch (adjust as needed)
  pull_request:
    branches:
      - main  # Optional: Trigger action on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials (hardcode the region here)
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'  # Hardcoded region (replace with your region)

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }} .

    # Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY_URI }}:latest ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
